spring.application.name=servicio-tvmaze-open-feign
tvmaze.api.url=https://api.tvmaze.com
tvmaze.mongodb.uri=mongodb+srv://josmarmorenov_db_user:M4S5GiTmtdY6TYmy@cluster0.ieivpae.mongodb.net/tvmaze?retryWrites=true&w=majority&appName=Cluster0
